name: CI

on:
  push:
    branches: [ performance-testing-benchmark ]
  pull_request:
    branches: [ performance-testing-benchmark ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13


    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go get -u github.com/jstemmer/go-junit-report
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        go get -u github.com/

    - name: Build
      run: go build -v ./...

    - name: Test
      run: | 
        mkdir test-results
        go test -v ./... 2>&1 | go-junit-report > ./test-results/unittest_report.xml

    - name: Test Benchmark
      run: | 
        go test -v -bench -run=XXX . -count 5 2>&1 | go-junit-report > ./test-results/benchmark_report.xml

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.6
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: test-results/**/*.xml